FROM --platform=linux/amd64 ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# various - postgres
RUN apt-get update && \
    apt-get install -y postgresql-client-14 jq

# various - kubernetes
RUN apt-get update && \
    apt-get install -y ca-certificates curl tzdata git unzip

# node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    . /root/.bashrc && nvm alias default v18.17 && nvm install v18.17 && nvm use v18.17 && rm -frv install.sh

# prettier
RUN . /root/.bashrc && npm install -g prettier@latest

# kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    mv kubectl /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# kustomize
RUN curl -sL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && \
    mv kustomize /usr/local/bin/kustomize && \
    chmod +x /usr/local/bin/kustomize && \
    rm -fv install_kustomize.sh

# AWSCLIv2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -frv awscliv2.zip aws /tmp/*

FROM --platform=linux/amd64 scratch

COPY --link --from=builder / /

WORKDIR /srv

ENV TZ=Etc/UTC

ENTRYPOINT ["/bin/bash"]
CMD []
