FROM --platform=linux/amd64 ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# various
RUN apt-get update && \
    apt-get install -y postgresql-client-14 jq

FROM --platform=linux/amd64 scratch

COPY --link --from=builder / /

WORKDIR /srv

ENV TZ=Etc/UTC

ENTRYPOINT ["/bin/bash"]
CMD []
